# Generated by Django 5.0.2 on 2024-02-27 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
        ('clientes', '0005_customer_files_alter_contract_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(max_length=10, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='service',
            name='problem',
            field=models.TextField(verbose_name='Problema'),
        ),
        migrations.AlterField(
            model_name='service',
            name='solution',
            field=models.TextField(verbose_name='Solução'),
        ),
        migrations.AlterField(
            model_name='service',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor'),
        ),
    ]
