# Generated by Django 5.0.2 on 2024-02-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_alter_service_customer_alter_service_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
