# Generated by Django 5.0.2 on 2024-02-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0005_alter_service_image_alter_service_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagem'),
        ),
    ]
