# Generated by Django 5.0.2 on 2024-02-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0006_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
