# Generated by Django 5.0.2 on 2024-02-21 19:43

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('date', models.DateField()),
                ('reminder', models.TextField()),
                ('image', models.ImageField(upload_to=[pathlib.PureWindowsPath('D:/Diogo/Projetos/radcom_manager_django/media/anotacoes')])),
            ],
            options={
                'verbose_name': 'Anotação',
                'verbose_name_plural': 'Anotações',
            },
        ),
    ]
