# Generated by Django 5.0.2 on 2024-02-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
