# Generated by Django 5.0.2 on 2024-03-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anotacoes', '0002_remove_annotation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='image',
        ),
    ]
