# Generated by Django 5.0.2 on 2024-02-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotacoes', '0002_alter_annotation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='reminder',
            field=models.TextField(verbose_name='Lembrete'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='title',
            field=models.CharField(max_length=99, verbose_name='Título'),
        ),
    ]
