# Generated by Django 5.0.2 on 2024-03-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(default='', max_length=99, verbose_name='Nome'),
        ),
    ]
