# Generated by Django 5.0.2 on 2024-02-27 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_customer_address_alter_customer_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='files',
            field=models.FileField(blank=True, upload_to='media/files', verbose_name='Arquivos'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('Internet', 'Internet'), ('Interfone', 'Interfone'), ('Internet/Interfone', 'Internet/Interfone')], max_length=18, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='equipment',
            field=models.TextField(blank=True, null=True, verbose_name='Equipamento'),
        ),
    ]
