# Generated by Django 5.0.2 on 2024-02-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_customer_files_alter_contract_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='files',
            field=models.FileField(blank=True, upload_to='files', verbose_name='Arquivos'),
        ),
    ]
