# Generated by Django 5.0.2 on 2024-02-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_customer_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='files/', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='files',
        ),
        migrations.AddField(
            model_name='customer',
            name='files',
            field=models.ManyToManyField(blank=True, to='clientes.file', verbose_name='Arquivos'),
        ),
    ]
