# Generated by Django 5.0.2 on 2024-02-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_file_remove_customer_files_customer_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
