# Generated by Django 5.0.2 on 2024-02-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_file_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='files',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
