# Generated by Django 4.2.10 on 2024-03-04 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('title', models.CharField(max_length=99, verbose_name='Título')),
                ('backup_pabx', models.FileField(blank=True, upload_to='files/pabx', verbose_name='Backup PABX')),
                ('backup_rb', models.FileField(blank=True, upload_to='files/rb', verbose_name='Backup RB')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
    ]
